### ISSUE TITLE
Prefer Rekapi or GSAP

### ISSUE THREAD

**Issue by joelburget** [gilbox/react-spark-scroll#6]
I'd like to be told which to use because I have no prior knowledge to compare them on. Would be nice to have a note -- "If you don't know either Rekapi or GSAP, use Rekapi" (or GSAP).

**Comment by gilbox** [comment]
Well, it depends... 
- GSAP is much easier to configure. That's because rekapi has some additional configuration necessary (see #3) beyond `npm install spark-scroll-rekapi`. If you're in the quick-and-dirty experimentation stage, use gsap to get up and running faster.
- Although I haven't done any benchmarks I suspect that rekapi is marginally faster than GSAP. That's because rekapi was built around the concept of timeline-based animation and spark-scroll is all about treating the scroll position as a timeline.
- **GSAP supports animating SVGs**. This is the main deciding factor for me. If I don't need SVG animation I prefer using rekapi although it's not a strong preference.
- Rekapi and GSAP have different licenses.

**Comment by gilbox** [comment]
closing this in light of PR #8
